variable "aws_profile" {
  type    = string
  default = "packer"
}

variable "instance_type" {
  type    = string
  default = "t3a-nano"
}

variable "region" {
  type    = string
  default = "cn-northwest-1"
}

data "amazon-ami" "autogenerated_1" {
  filters     = {
    name                = "Amazon Linux AMI-*"
    root-device-type    = "ebs"
    virtualization-type = "hvm"
  }
  most_recent = true
  owners      = ["amazon"]
  profile     = "${var.aws_profile}"
  region      = "${var.region}"
}

source "amazon-ebs" "autogenerated_1" {
  ami_description = "Amazon Linux Image with Jenkins Server"
  ami_name        = "jenkins-master-2.204.1"
  instance_type   = "${var.instance_type}"
  profile         = "${var.aws_profile}"
  region          = "${var.region}"
  source_ami      = "${data.amazon-ami.autogenerated_1.id}"
  ssh_username    = "ec2-user"
}

build {
  sources = ["source.amazon-ebs.autogenerated_1"]

  provisioner "shell" {
    execute_command = "sudo -E -S sh '{{ .Path }}'"
    script          = "./setup.sh"
  }

}
